# These are supported funding model platforms

github: ['jgulick48'] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
custom: ['https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=WEA6SHVCJQNQG&source=url'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
