FROM golang:1.20.5 as builder

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY ./ ./

RUN go test ./...

RUN GOOS=linux GOARCH=arm64 GOARM=5 CGO_ENABLED=0 go build

FROM alpine:3.20.1

COPY --from=builder /app/rv-homekit /bin/rv-homekit
WORKDIR /var/lib/rv-homekit/

CMD ["/bin/rv-homekit","-configFile=/var/lib/rv-homekit/config.json"]
